<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.2">
  <POU Name="Version" Id="{d6c83722-516d-49df-a8e5-5c93c1595c06}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Version
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[(*

1.0.2.2:	Boido	010120

Added VersionLib and Verstion.txt to the project.

1.0.3.3:	Boido	010120

SymbolPathStorage added to the project.
IO FBs like BoolIn and BoolOut extend SymbolPathStorage in order to have and 
easy way to group all symbol paths in a central storage and make it accessible 
to an ADS interface.

1.0.4.4:	Boido	020120

Version.txt replaced with Version PRG

1.0.5.5:	Boido	020120

VersionLib removed.

1.0.6.6:	Boido	020120

String replaced with T_MaxString: BoolIn,BoolOut,SymbolPathStorage

1.1.0.7:	Boido	020120

Separation between "BoolIn" and "BoolOut" paths.

1.2.0.8:	Boido	040120

Added a timer to the FB_StepWorker.
If the timer is set up, mNextStep() will wait for the timer to reach the configured time 
before releasing the next step.

1.2.1.9:	Boido	040120

mSetTimer and mNextStep added to I_StepWorker interface

2.0.0.10:	Boido	080120

Positive and negative condition check added to FB_StepWorker.
Adapted naming convention.

*)]]></ST>
    </Implementation>
    <LineIds Name="Version">
      <LineId Id="5" Count="0" />
      <LineId Id="7" Count="0" />
      <LineId Id="20" Count="8" />
      <LineId Id="8" Count="0" />
      <LineId Id="29" Count="0" />
      <LineId Id="9" Count="0" />
      <LineId Id="31" Count="0" />
      <LineId Id="30" Count="0" />
      <LineId Id="36" Count="0" />
      <LineId Id="38" Count="1" />
      <LineId Id="37" Count="0" />
      <LineId Id="44" Count="2" />
      <LineId Id="43" Count="0" />
      <LineId Id="49" Count="2" />
      <LineId Id="32" Count="0" />
      <LineId Id="56" Count="0" />
      <LineId Id="52" Count="0" />
      <LineId Id="58" Count="0" />
      <LineId Id="57" Count="0" />
      <LineId Id="59" Count="0" />
      <LineId Id="61" Count="0" />
      <LineId Id="63" Count="0" />
      <LineId Id="62" Count="0" />
      <LineId Id="65" Count="0" />
      <LineId Id="64" Count="0" />
      <LineId Id="70" Count="0" />
      <LineId Id="69" Count="0" />
      <LineId Id="73" Count="0" />
      <LineId Id="72" Count="0" />
      <LineId Id="74" Count="1" />
      <LineId Id="6" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>